name: flutter_base_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_info_plus: ^3.1.0
  connectivity_plus: ^2.0.2
  dio: ^4.0.1
  equatable: ^2.0.3
  dartz: ^0.10.0
  json_annotation: ^4.3.0
  flutter_staggered_grid_view: ^0.4.1

  firebase_core: ^1.10.6
  firebase_analytics: ^9.0.4
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  firebase_crashlytics: ^2.4.4

  # RxDart extends the capabilities of Dart Streams and StreamControllers.
  rxdart: ^0.27.3

  # Super-fast Flutter database for storing and syncing Dart objects
  objectbox: ^1.3.0

  # provide annotation for DI
  injectable: ^1.5.3

  # DI
  get_it: ^7.2.0

  # local storage
  shared_preferences: ^2.0.12

  # holding data
  tuple: ^2.0.0

  # log
  logger: ^1.1.0

  provider: ^6.0.2

  pretty_dio_logger: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  injectable_generator: ^1.5.3
  json_serializable: ^6.0.1
  flutter_native_splash: ^1.3.2

flutter_native_splash:
  color: "#6F35A5"
  image: assets/logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
